# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4htDzxF9XlFgFRofZrj8HAoPXdGB89W
"""

#Entradas do usuário
nome = input('Informe seu nome: ')
print('Olá',nome, 'vamos começar o exercicio!')
num1 = input('Digite um número: ')
num2 = input('Digite outro número: ')

#Convertando variaveis num1 e num2 para inteirop
num1_convert = int(num1)
num2_convert = int(num2)

#informando ao usuario qual opção deseja realizar
print('Para adição: 1 / Subtração: 2 / Multiplicação: 3 / Divisão: 4')

num = input('Digite o número da operação matemática em que deseja realizar: ')
num_convert = int(num)

#condição para a opção em que o usuario informa no input anterior
if num_convert == 1:
  print('Operação de adição')
  print(num1_convert,'+',num2_convert,'=',num1_convert + num2_convert)
elif num_convert == 2:
  print('Operação de subtração')
  print(num1_convert,'-',num2_convert,'=',num1_convert - num2_convert)
elif num_convert == 3:
  print('Operação de multiplicação')
  print(num1_convert,'*',num2_convert,'=',num1_convert * num2_convert)
elif num_convert == 4:
  print('Operação de divisão')
  print(num1_convert,'/',num2_convert,'=',num1_convert / num2_convert)
else:
  print('Número inválido')